### PR TITLE
Another check for invalid row parameter.

### PR DESCRIPTION
**Pull request by vranki**
Don't crash if invalid row is given. Not tested properly, but looks trivial.

### CODE REVIEW

**Comment by thp** [comment]
@vranki do you think you can rework it with the feedback from Pekka?

**Comment by vranki** [comment]
Yep, I'll do it. Hopefully next week.

**Comment by vranki** [comment]
I looked at this and rebase & squash would be a pretty complex job as this is done in master branch and includes some merge conflict fixes. I suggest you just accept the pull request and I'll try to remember squashing next time. The end result should work anyway.

**Comment by chriadam** [comment]
Alternative is to just do:

    git diff nemomobile/master > ../diff1.diff
    git reset --hard nemomobile/master
    git apply ../diff1.diff
    git commit -a -m "Check rows to avoid crash if invalid row is given."
    git push --force vranki master:master

That will ensure just a single commit, on top of the latest history.

**Comment by thp** [comment]
Or `git rebase -i nemomobile/master` and reorder/squash/fixup commits.

**Comment by thp** [comment]
@vranki I've rebased your commits here: https://github.com/nemomobile/nemo-qml-plugin-contacts/tree/invalid-row-parameter-check

Please have a look if these are the changes you want and if so, we can get this merged.

**Comment by vranki** [comment]
LGTM

**Comment by thp** [comment]
Continued here: https://github.com/nemomobile/nemo-qml-plugin-contacts/pull/121

**Pull request closed without merging**
